

module AbsGo where

-- Haskell module generated by the BNF converter




newtype CIdent = CIdent String deriving (Eq, Ord, Show, Read)
data Boolean = Boolean_true | Boolean_false
  deriving (Eq, Ord, Show, Read)

data RExp
    = Or RExp RExp
    | And RExp RExp
    | Not RExp
    | Eq RExp RExp
    | Neq RExp RExp
    | Lt RExp RExp
    | LtE RExp RExp
    | Gt RExp RExp
    | GtE RExp RExp
    | Add RExp RExp
    | Sub RExp RExp
    | Mul RExp RExp
    | Div RExp RExp
    | Mod RExp RExp
    | Neg RExp
    | Ref LExp
    | Deref RExp
    | FCall FunCall
    | Int Integer
    | Float Double
    | Char Char
    | String String
    | Bool Boolean
    | LExprex LExp
  deriving (Eq, Ord, Show, Read)

data LExp
    = PostInc LExp | PostDecr LExp | BLExprex BLexp | LExpId CIdent
  deriving (Eq, Ord, Show, Read)

data BLexp = ExpArr BLexp RExp | ExpArrId CIdent RExp
  deriving (Eq, Ord, Show, Read)

data Program = Prog CIdent [CompStatement]
  deriving (Eq, Ord, Show, Read)

data BasicType
    = BasicType_void
    | BasicType_bool
    | BasicType_char
    | BasicType_float
    | BasicType_int
    | BasicType_string
    | BasicType1 Integer BasicType
    | BasicType2 BasicType
  deriving (Eq, Ord, Show, Read)

data Decl
    = DeclVar [CIdent] BasicType
    | DeclVarInit [CIdent] [RExp]
    | DeclVarInitType [CIdent] BasicType [RExp]
    | DeclVarShort [CIdent] [RExp]
  deriving (Eq, Ord, Show, Read)

data DeclFun = DeclF CIdent [Param] BasicType Block
  deriving (Eq, Ord, Show, Read)

data Param = ParamL [CIdent] BasicType
  deriving (Eq, Ord, Show, Read)

data Block = BodyBlock [CompStatement]
  deriving (Eq, Ord, Show, Read)

data FunCall = ExpFuncEmpty CIdent | ExpFunc CIdent [RExp]
  deriving (Eq, Ord, Show, Read)

data Statement
    = StateBlock Block
    | StateDecl Decl
    | StateDeclFun DeclFun
    | StateFunCall FunCall
    | StateExp LExp
    | StateAsgn LExp Assignment_op RExp
    | StateReturn RExp
    | StateBreak
    | StateContinue
    | StateWrite WriteType RExp
    | StateRead ReadType
  deriving (Eq, Ord, Show, Read)

data Assignment_op
    = Assign | AssgnMul | AssgnAdd | AssgnDiv | AssgnSub
  deriving (Eq, Ord, Show, Read)

data CompStatement
    = CompStmt Statement
    | StateIf RExp Block
    | StateIfElse RExp Block Block
    | StateIfStm Statement RExp Block
    | StateIfElseStm Statement RExp Block Block
    | StateFor Statement RExp Statement Block
    | StateWhile RExp Block
  deriving (Eq, Ord, Show, Read)

data WriteType
    = WriteType_writeInt
    | WriteType_writeFloat
    | WriteType_writeChar
    | WriteType_writeString
  deriving (Eq, Ord, Show, Read)

data ReadType
    = ReadType_readInt
    | ReadType_readFloat
    | ReadType_readChar
    | ReadType_readString
  deriving (Eq, Ord, Show, Read)

