{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintGo where

-- pretty-printer generated by the BNF converter

import AbsGo
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)



instance Print Id where
  prt _ (Id i) = doc (showString ( i))
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])


instance Print Start where
  prt i e = case e of
    Entry id decls -> prPrec i 0 (concatD [doc (showString "package"), prt 0 id, prt 0 decls])

instance Print Decl where
  prt i e = case e of
    DeclFun id params type_ block -> prPrec i 0 (concatD [doc (showString "func"), prt 0 id, doc (showString "("), prt 0 params, doc (showString ")"), prt 0 type_, prt 0 block])
    DeclProc id params block -> prPrec i 0 (concatD [doc (showString "func"), prt 0 id, doc (showString "("), prt 0 params, doc (showString ")"), doc (showString "void"), prt 0 block])
    DeclVar ids type_ -> prPrec i 0 (concatD [doc (showString "var"), prt 0 ids, prt 0 type_])
    DeclVarInit ids rexps -> prPrec i 0 (concatD [doc (showString "var"), prt 0 ids, doc (showString "="), prt 0 rexps])
    DeclVarTypeInit ids type_ rexps -> prPrec i 0 (concatD [doc (showString "var"), prt 0 ids, prt 0 type_, doc (showString "="), prt 0 rexps])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print ShortVarDecl where
  prt i e = case e of
    DeclVarShort ids rexps -> prPrec i 0 (concatD [prt 0 ids, doc (showString ":="), prt 0 rexps])

instance Print Param where
  prt i e = case e of
    ParamL ids type_ -> prPrec i 0 (concatD [prt 0 ids, prt 0 type_])
    ParamLPassType pass ids type_ -> prPrec i 0 (concatD [prt 0 pass, prt 0 ids, prt 0 type_])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Pass where
  prt i e = case e of
    PassValue -> prPrec i 0 (concatD [doc (showString "val")])
    PassRef -> prPrec i 0 (concatD [doc (showString "ref")])
    PassValueRes -> prPrec i 0 (concatD [doc (showString "valres")])

instance Print Type where
  prt i e = case e of
    TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    TInt -> prPrec i 0 (concatD [doc (showString "int")])
    TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    TFloat -> prPrec i 0 (concatD [doc (showString "float")])
    TChar -> prPrec i 0 (concatD [doc (showString "char")])
    TString -> prPrec i 0 (concatD [doc (showString "string")])
    TArray n type_ -> prPrec i 0 (concatD [doc (showString "["), prt 0 n, doc (showString "]"), prt 0 type_])
    TPointer type_ -> prPrec i 0 (concatD [doc (showString "*"), prt 0 type_])

instance Print Block where
  prt i e = case e of
    BodyBlock stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print Stmt where
  prt i e = case e of
    StBlock block -> prPrec i 0 (concatD [prt 0 block])
    StSmpl stmtsmpl -> prPrec i 0 (concatD [prt 0 stmtsmpl])
    StReturn rexp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 rexp])
    StIf rexp block -> prPrec i 0 (concatD [doc (showString "if"), prt 0 rexp, prt 0 block])
    StIfElse rexp block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 rexp, prt 0 block1, doc (showString "else"), prt 0 block2])
    StIfStm stmtsmpl rexp block -> prPrec i 0 (concatD [doc (showString "if"), prt 0 stmtsmpl, doc (showString ";"), prt 0 rexp, prt 0 block])
    StIfElseStm stmtsmpl rexp block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 stmtsmpl, doc (showString ";"), prt 0 rexp, prt 0 block1, doc (showString "else"), prt 0 block2])
    StFor stmtsmpls1 rexp stmtsmpls2 block -> prPrec i 0 (concatD [doc (showString "for"), prt 0 stmtsmpls1, doc (showString ";"), prt 0 rexp, doc (showString ";"), prt 0 stmtsmpls2, prt 0 block])
    StWhile rexp block -> prPrec i 0 (concatD [doc (showString "for"), prt 0 rexp, prt 0 block])
    StDecl decl -> prPrec i 0 (concatD [prt 0 decl])
    StBreak -> prPrec i 0 (concatD [doc (showString "break")])
    StContinue -> prPrec i 0 (concatD [doc (showString "continue")])
    StTryCatch block1 block2 -> prPrec i 0 (concatD [doc (showString "try"), prt 0 block1, doc (showString "catch"), prt 0 block2])
    StWrite rexp -> prPrec i 0 (concatD [doc (showString "write"), doc (showString "("), prt 0 rexp, doc (showString ")")])
    StRead rexp -> prPrec i 0 (concatD [doc (showString "read"), doc (showString "("), prt 0 rexp, doc (showString ")")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print StmtSmpl where
  prt i e = case e of
    StShortVarDecl shortvardecl -> prPrec i 0 (concatD [prt 0 shortvardecl])
    StExp rexp -> prPrec i 0 (concatD [prt 0 rexp])
    StAsgn lexp rexp -> prPrec i 0 (concatD [prt 0 lexp, doc (showString "="), prt 0 rexp])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
instance Print LExp where
  prt i e = case e of
    ExpId id -> prPrec i 0 (concatD [prt 0 id])
    ExpArr lexp rexp -> prPrec i 0 (concatD [prt 0 lexp, doc (showString "["), prt 0 rexp, doc (showString "]")])
    ExpDeref rexp -> prPrec i 0 (concatD [doc (showString "*"), prt 0 rexp])

instance Print RExp where
  prt i e = case e of
    ExpAdd rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "+"), prt 0 rexp2])
    ExpSub rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "-"), prt 0 rexp2])
    ExpMul rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "*"), prt 0 rexp2])
    ExpDiv rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "/"), prt 0 rexp2])
    ExpMod rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "%"), prt 0 rexp2])
    ExpEq rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "=="), prt 0 rexp2])
    ExpNeq rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "!="), prt 0 rexp2])
    ExpLt rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "<"), prt 0 rexp2])
    ExpLtE rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "<="), prt 0 rexp2])
    ExpGt rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString ">"), prt 0 rexp2])
    ExpGtE rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString ">="), prt 0 rexp2])
    ExpAnd rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "&&"), prt 0 rexp2])
    ExpOr rexp1 rexp2 -> prPrec i 0 (concatD [prt 0 rexp1, doc (showString "||"), prt 0 rexp2])
    ExpNot rexp -> prPrec i 0 (concatD [doc (showString "!"), prt 0 rexp])
    ExpNeg rexp -> prPrec i 0 (concatD [doc (showString "-"), prt 0 rexp])
    ExpVal value -> prPrec i 0 (concatD [prt 0 value])
    ExpLef lexp -> prPrec i 0 (concatD [prt 0 lexp])
    ExpFuncEmpty id -> prPrec i 0 (concatD [prt 0 id, doc (showString "("), doc (showString ")")])
    ExpFunc id rexps -> prPrec i 0 (concatD [prt 0 id, doc (showString "("), prt 0 rexps, doc (showString ")")])
    ExpRef lexp -> prPrec i 0 (concatD [doc (showString "&"), prt 0 lexp])
    ExpPar rexp -> prPrec i 0 (concatD [doc (showString "("), prt 0 rexp, doc (showString ")")])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print Value where
  prt i e = case e of
    Int n -> prPrec i 0 (concatD [prt 0 n])
    Float d -> prPrec i 0 (concatD [prt 0 d])
    Char c -> prPrec i 0 (concatD [prt 0 c])
    String str -> prPrec i 0 (concatD [prt 0 str])
    Bool boolean -> prPrec i 0 (concatD [prt 0 boolean])

instance Print Boolean where
  prt i e = case e of
    Boolean_true -> prPrec i 0 (concatD [doc (showString "true")])
    Boolean_false -> prPrec i 0 (concatD [doc (showString "false")])


