{-# OPTIONS -fno-warn-incomplete-patterns #-}
module PrintGo where

-- pretty-printer generated by the BNF converter

import AbsGo
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
  -- "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> shiftBack (i-1) . showChar '}' . rend (i-1) ts
  -- ";"      :ts -> showChar ';' .space "" . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
    
  new i        = showChar '\n' . replicateS ((4*i)+2) (showChar ' ') . dropWhile isSpace
  shiftBack i  = replicateS ((4*i)+1) (showChar ' ') . dropWhile isSpace
  space t      = showString t . (\s -> if null s then "" else (' ':s))


parenth :: Doc -> Doc
parenth ss = ss . doc (showString "\n")


concatS :: [ShowS] -> ShowS
concatS = foldr (.) id


concatD :: [Doc] -> Doc
concatD = foldr (.) id


replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)


-- the printer class does the job
class Print a where
  prt :: Int -> Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList t = concatD . map (prt 0 t)


instance Print a => Print [a] where
  prt _ t = prtList t


instance Print Char where
  prt _ _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList t s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')


mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s


prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ _ x = doc (shows x)


instance Print Double where
  prt _ _ x = doc (shows x)


instance Print Boolean where
  prt i t e = case e of
   Boolean_true  -> prPrec i 0 (concatD [doc (showString "true")])
   Boolean_false  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print Id where
  prt _ t (Id i) = doc (showString ( i))
  prtList  t es = case es of
   [x] -> (concatD [prt 0 t x])
   x:xs -> (concatD [prt 0 t x , doc (showString ",") , prt 0 t xs])


instance Print Type where
  prt i t e = case e of
   TInt  -> prPrec i 0 (concatD [doc (showString "int")])
   TBool  -> prPrec i 0 (concatD [doc (showString "bool")])
   TFloat  -> prPrec i 0 (concatD [doc (showString "float")])
   TChar  -> prPrec i 0 (concatD [doc (showString "char")])
   TString  -> prPrec i 0 (concatD [doc (showString "string")])
   TArray n type' -> prPrec i 0 (concatD [doc (showString "[") , prt 0 t n , doc (showString "]") , prt 0 t  type'])
   TPointer type' -> prPrec i 0 (concatD [doc (showString "*") , prt 0 t type'])


instance Print Start where
  prt i t e = case e of
   Entry id decls -> prPrec i 0 (concatD [ doc (showString "package") , prt 0 t id , doc (showString "\n")  , prt 0 t decls])


instance Print Decl where
  prt i t e = case e of
   DeclVar ids type' -> prPrec i 0 (concatD [doc (showString "var") , prt 0 t ids , prt 0 t type'])
   DeclVarInit ids exprs -> prPrec i 0 (concatD [doc (showString "var") , prt 0 t ids , doc (showString "=") , prt 0 t exprs])
   DeclVarTypeInit ids type_ rexps -> prPrec i 0 (concatD [doc (showString "var"), prt 0 t ids, prt 0 t type_, doc (showString "="), prt 0 t rexps])
   DeclFun id params type' block -> prPrec i 0 (concatD [doc (showString "func") , prt 0 t id , doc (showString "(") , prt 0  t params , doc (showString ")") , prt 0 t type' , prt 0 t block])
   DeclProc id params block -> prPrec i 0 (concatD [doc (showString "func") , prt 0 t id , doc (showString "(") , prt 0 t params , doc (showString ")") , prt 0 t block])
  
  prtList t [] = (concatD [])
  prtList t (x:xs) = (concatD [prt t 0 x,  doc (showString "\n"), prt t 0 xs])


instance Print ShortVarDecl where
  prt i t e = case e of
   DeclVarShort ids exprs -> prPrec i 0 (concatD [prt t 0 ids , doc (showString ":=") , prt t 0 exprs])


instance Print Param where
  prt i t e = case e of
   Parameter ids type' -> prPrec i 0 (concatD [prt 0 t ids , prt 0 t type'])
   ParameterPass pass ids type' -> prPrec i 0 (concatD [prt 0 t pass , prt 0 t ids , prt 0 t type'])

  prtList t [] = (concatD [])
  prtList t [x] = (concatD [prt 0 t x])
  prtList t (x:xs) = (concatD [prt 0 t x, doc (showString ","), prt 0 t xs])


instance Print Pass where
  prt i t e = case e of
   PassVal  -> prPrec i 0 (concatD [doc (showString "val")])
   PassRef  -> prPrec i 0 (concatD [doc (showString "ref")])


instance Print Block where
  prt i t e = case e of
   BodyBlock statements -> prPrec i 0 (concatD [doc (showString "{") , prt 0 (t+1) statements , doc (showString "}")])


instance Print Stmt where
  prt i t e = case e of
   StDecl decl -> prPrec i 0 (concatD [prt 0 t  decl])
   StBlock block -> prPrec i 0 (concatD [ prt 0 t block])
   StSmpl statementsmpl -> prPrec i 0 (concatD [ prt 0 t statementsmpl])
   StIf expr block -> prPrec i 0 (concatD [doc (showString "if") , prt 0 t expr , prt 0 t block])
   StIfElse expr block0 block -> prPrec i 0 (concatD [doc (showString "if") , prt 0 t expr , prt 0 t  block0 , doc (showString "else") , prt 0 t block])
   StWhile expr block -> prPrec i 0 (concatD [doc (showString "for") , prt 0 t  expr , prt 0 t  block])
   StBreak  -> prPrec i 0 (concatD [doc (showString "break")])
   StContinue  -> prPrec i 0 (concatD [doc (showString "continue")])
   StReturn expr -> prPrec i 0 (concatD [doc (showString "return") , prt 0 t expr])
   StWrite writet rexp -> prPrec i 0 (concatD [prt 0 t writet, doc (showString "("), prt 0 t rexp, doc (showString ")")])

  prtList t [] = (concatD [])
  prtList t (x:xs) = (concatD [doc ( replicateS (4*t) (showChar ' ')) , prt 1 t x,  prt 1 t xs])


instance Print WriteT where
  prt i t e = case e of
    WriteT_writeInt -> prPrec i 0 (concatD [doc (showString "writeInt")])
    WriteT_writeFloat -> prPrec i 0 (concatD [doc (showString "writeFloat")])
    WriteT_writeChar -> prPrec i 0 (concatD [doc (showString "writeChar")])
    WriteT_writeString -> prPrec i 0 (concatD [doc (showString "writeString")])
   

instance Print StmtSmpl where
  prt i t e = case e of
   StShortVarDecl shortvardecl -> prPrec i 0 (concatD [prt 0 t   shortvardecl])
   StExp expr -> prPrec i 0 (concatD [prt 0 t   expr])
   StAsgn expl expr -> prPrec i 0 (concatD [prt 0 t  expl , doc (showString "=") , prt 0 t  expr])
  
  prtList t []  = (concatD [])
  prtList t [x] = (concatD [prt 0 t x])
  

instance Print LExp where
  prt i t e = case e of
   ExpId id -> prPrec i 0 (concatD [prt 0 t  id])
   ExpArr expl expr -> prPrec i 0 (concatD [prt 0 t  expl , doc (showString "[") , prt 0 t  expr , doc (showString "]")])
   ExpDeref expr -> prPrec i 0 (concatD [doc (showString "*") , prt 0 t  expr])


instance Print RExp where
  prt i t e = case e of
   ExpAnd expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "&&") , prt 0 t  expr])
   ExpOr expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "||") , prt 0 t  expr])
   ExpNot expr -> prPrec i 0 (concatD [doc (showString "!") , prt 0 t  expr])
   ExpEq expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "==") , prt 0 t  expr])
   ExpNeq expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "!=") , prt 0 t  expr])
   ExpLt expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "<") , prt 0 t  expr])
   ExpLtE expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "<=") , prt 0 t  expr])
   ExpGt expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString ">") , prt 0 t  expr])
   ExpGtE expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString ">=") , prt 0 t  expr])
   ExpAdd expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "+") , prt 0 t  expr])
   ExpSub expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "-") , prt 0 t  expr])
   ExpMul expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "*") , prt 0 t  expr])
   ExpDiv expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "/") , prt 0 t  expr])
   ExpMod expr0 expr -> prPrec i 0 (concatD [prt 0 t  expr0 , doc (showString "%") , prt 0 t  expr])
   ExpNeg expr -> prPrec i 0 (concatD [doc (showString "-") , prt 0 t  expr])
   ExpRef expl -> prPrec i 0 (concatD [doc (showString "&") , prt 0 t  expl])
   ExpFuncEmpty id -> prPrec i 0 (concatD [prt 0 t  id , doc (showString "(") , doc (showString ")")])
   ExpFunc id exprs -> prPrec i 0 (concatD [prt 0 t  id , doc (showString "(") , prt 0 t  exprs , doc (showString ")")])
   ExpVal value -> prPrec i 0 (concatD [prt 0 t  value])
   ExpLExp expl -> prPrec i 0 (concatD [prt 0 t  expl])
   ExpPar expr -> prPrec i 0 (concatD [doc (showString "(") , prt 0 t  expr , doc (showString ")")])
   StRead readt -> prPrec i 0 (concatD [prt 0 t readt, doc (showString "("), doc (showString ")")])

  prtList t [x] = (concatD [prt 0 t x])
  prtList t (x:xs) = (concatD [prt 0 t x, doc (showString ","), prt 0 t xs])


instance Print ReadT where
  prt i t e = case e of
    ReadT_readInt -> prPrec i 0 (concatD [doc (showString "readInt")])
    ReadT_readFloat -> prPrec i 0 (concatD [doc (showString "readFloat")])
    ReadT_readChar -> prPrec i 0 (concatD [doc (showString "readChar")])
    ReadT_readString -> prPrec i 0 (concatD [doc (showString "readString")])
    

instance Print Val where
  prt i t e = case e of
   Int n -> prPrec i 0 (concatD [prt 0 t  n])
   Float d -> prPrec i 0 (concatD [prt 0 t  d])
   Char c -> prPrec i 0 (concatD [prt 0 t  c])
   String str -> prPrec i 0 (concatD [prt 0 t  str])
   Bool boolean -> prPrec i 0 (concatD [prt 0 t  boolean])





